language: minimal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - |
    set -e
    if ! docker build . -f Dockerfile -t $DOCKER_USERNAME/the_doctor:latest; then
      echo "Docker build failed."
      exit 1
    fi

after_success:
  - |
    set -e
    if ! docker push $DOCKER_USERNAME/the_doctor:latest; then
      echo "Docker push failed."
      exit 1
    fi
