language: minimal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t $DOCKER_USERNAME/the_doctor:latest TheDoctor/

after_success:
  - docker push $DOCKER_USERNAME/the_doctor:latest
