language: minimal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t $DOCKER_USERNAME/the_doctor:latest TheDoctor/
  - |
      if [ -n "$TRAVIS_TAG" ]; then
        docker tag $DOCKER_USERNAME/the_doctor:latest $DOCKER_USERNAME/the_doctor:$TRAVIS_TAG
      fi

after_success:
  - docker push $DOCKER_USERNAME/the_doctor:latest
